"""add description to products

Revision ID: 822373fdb64a
Revises: ec1580e62385
Create Date: 2020-01-23 11:12:58.113759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822373fdb64a'
down_revision = 'ec1580e62385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
